### PR TITLE
Overzooming and max zoom adjustment

### PR DESCRIPTION
**Pull request by jpolchlo**
Previously, the GeoNotebook map interface was constrained to zoom levels less than or equal to 16.  We can now adjust the range of permissible zoom levels using a statement of the form `M.set_zoom_range(0,22)`.  One may also use `M.set_max_zoom(22)`.  Now, `M.set_center` can utilize zoom values up to 22.

This PR also adds functionality for overzooming.

This PR fixes #4

### CODE REVIEW

**Comment by lossyrob** [comment]
@jpolchlo does this PR supersede #4 ?

**Comment by jpolchlo** [comment]
It should.  Rather than make PRs against your repo, I figured I would just grab your branch, fix it up and PR directly here.

**Comment by lossyrob** [comment]
Cool, I'll close the other one.

**Comment by jpolchlo** [comment]
This PR is out of date, and the overzooming functionality has been subsumed into the GeoPySpark TMS server.  Moreover, with the anticipated move to using the base Ktile vis server, the Geotrellis server will go away and this code will just disappear.  Closing.

**Pull request closed without merging**
